import React, { useEffect, useState } from "react";
import {
 login, validateSession, getYears, getDashboard, getDonations, getExpenditures,
 getPublicYears, getPublicDashboard, getPublicDonations, getPublicExpenditures,
 addDonation, addExpenditure, updateDonation, deleteDonation, updateExpenditure, deleteExpenditure, closeYear, getUsers, createUser
} from "./services/api";
import { LayoutDashboard, Heart, Receipt, CalendarClock, Users, LogOut, UserCircle, ChevronDown, Wallet, ShoppingCart, IndianRupee, Plus, LockKeyhole, X } from "lucide-react";

const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);

function Login({onLogin,onHome}){
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError("");try{const r=await login(username,password);localStorage.setItem("token",r.token);localStorage.setItem("user",JSON.stringify(r));onLogin(r)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="login-page"><form className="login-card" onSubmit={submit}><div className="login-diya">🪔</div><h1>श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर</h1><p>Secure Admin / Member Login</p>{error&&<div className="error">{error}</div>}<label>Username</label><input required value={username} onChange={e=>setUsername(e.target.value)}/><label>Password</label><input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="login-button">{busy?"Signing in...":"Sign In"}</button><button type="button" className="secondary" onClick={onHome}>← Public Home</button></form></div>
}

function PublicHome({onLogin}){
 const [years,setYears]=useState([]),[year,setYear]=useState(2026),[dash,setDash]=useState(null),[don,setDon]=useState([]),[exp,setExp]=useState([]),[view,setView]=useState("dashboard");
 useEffect(()=>{getPublicYears().then(y=>{setYears(y);if(y.length)setYear(Number(y[0].year))}).catch(()=>{})},[]);
 useEffect(()=>{if(!year)return;(async()=>{try{const [d,a,b]=await Promise.all([getPublicDashboard(year),getPublicDonations(year),getPublicExpenditures(year)]);setDash(d);setDon(a);setExp(b)}catch(e){console.error(e)}})()},[year]);
 return <div className="public-page"><header className="public-header"><div className="public-brand"><div className="public-logo">🪔</div><div><h2>श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर</h2><p>Community Contribution & Expenditure Ledger</p></div></div><div className="public-actions"><div className="year-picker"><b>Year:</b><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y.year}>{y.year}</option>)}</select></div><button className="public-login" onClick={onLogin}>Admin Login</button></div></header><main className="public-content">
  {view==="dashboard"&&dash&&<><section className="community-hero"><div className="community-photo-wrap"><img src="/community-photo.jpeg" alt="श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर community members" className="community-photo"/></div><div className="community-copy"><div className="hero-kicker">COMMUNITY • TRANSPARENCY • CELEBRATION</div><h1>श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर</h1><p>हमारे समुदाय के चंदा संग्रह और खर्च का पारदर्शी, वर्षवार सार्वजनिक लेखा-जोखा।</p><p className="hero-english">A transparent public record of community contributions and expenditures, maintained year by year.</p><div className="hero-year">Pooja Year {year}</div></div></section><div className="stats"><Stat title="OPENING BALANCE" amount={dash.openingBalance} icon={<Wallet/>} type="blue"/><Stat title="TOTAL DONATIONS" amount={dash.totalDonations} icon={<Heart/>} type="green" link="View Donations" onClick={()=>setView("donations")}/><Stat title="TOTAL EXPENDITURE" amount={dash.totalExpenditure} icon={<ShoppingCart/>} type="red" link="View Expenditures" onClick={()=>setView("expenditures")}/><Stat title="AVAILABLE BALANCE" amount={dash.availableBalance} icon={<IndianRupee/>} type="yellow"/></div><div className="public-panels"><div className="table-card public-summary-card"><h2>Donation Records</h2><p><strong>{don.length}</strong> donation records for {year}</p><button onClick={()=>setView("donations")}>View all donations →</button></div><div className="table-card public-summary-card"><h2>Expenditure Records</h2><p><strong>{exp.length}</strong> expenditure records for {year}</p><button onClick={()=>setView("expenditures")}>View all expenditures →</button></div></div><div className="public-footer">श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर • Community Transparency Ledger</div></>}
  {view==="donations"&&<PublicTable title={`All Donations — ${year}`} rows={don} type="donation" back={()=>setView("dashboard")}/>} {view==="expenditures"&&<PublicTable title={`All Expenditures — ${year}`} rows={exp} type="expense" back={()=>setView("dashboard")}/>}</main></div>
}
function Stat({title,amount,icon,type,link,onClick}){return <div className={`stat ${type} ${link?"clickable":""}`} onClick={onClick}><div className="stat-top"><div className="stat-icon">{icon}</div><div className="stat-title">{title}</div></div><div className="stat-amount">{money(amount)}</div>{link&&<div className="stat-link">{link} →</div>}</div>}
function PublicTable({title,rows,type,back}){return <section className="table-card"><div className="table-head"><h2>{title}</h2><button onClick={back}>← Back</button></div><div className="table-scroll"><table><thead><tr>{type==="donation"?<><th>Date</th><th>Donor</th><th>Mode</th><th>Amount</th></>:<><th>Date</th><th>Item / Service</th><th>Category</th><th>Vendor / Receipt</th><th>Amount</th></>}</tr></thead><tbody>{rows.map(r=>type==="donation"?<tr key={r.id}><td>{r.donationDate}</td><td>{r.donorName}</td><td>{r.paymentMode}</td><td className="right">{money(r.amount)}</td></tr>:<tr key={r.id}><td>{r.expenseDate}</td><td>{r.title}</td><td>{r.category}</td><td>{r.vendor||r.receiptReference||"—"}</td><td className="right">{money(r.amount)}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>No records.</td></tr>}</tbody></table></div></section>}

function Sidebar({page,setPage,role}){const items=[["dashboard",<LayoutDashboard size={20}/> ,"Dashboard"],["donations",<Heart size={20}/> ,"Donations"],["expenditures",<Receipt size={20}/> ,"Expenditures"],["year",<CalendarClock size={20}/> ,"Year Closure"],...(role==="ADMIN"?[["users",<Users size={20}/> ,"Users"]]:[])];return <aside className="sidebar"><div className="sidebar-logo"><div className="diya">🪔</div><div><h2>लक्ष्मी पूजा समिति</h2><span>मुस्तफापुर</span></div></div><nav>{items.map(([k,i,l])=><button key={k} className={`sidebar-item ${page===k?"active":""}`} onClick={()=>setPage(k)}>{i}<span>{l}</span></button>)}</nav></aside>}
function Topbar({year,setYear,years,user,onLogout}){return <header className="topbar"><div className="brand"><div className="brand-icon">🪔</div><div><h2>श्री श्री लक्ष्मी पूजा समिति मुस्तफापुर</h2><p>Authenticated Financial Dashboard</p></div></div><div className="topbar-actions"><div className="year-picker"><b>Year:</b><select value={year??""} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y.year} value={y.year}>{y.year}</option>)}</select></div><span className="role">{user.role}</span><UserCircle className="topbar-user-icon" size={30}/><button className="logout-button" onClick={onLogout}><LogOut size={18}/><span>Logout</span></button></div></header>}

function Editor({type,initial,onClose,onSaved,year}){const donation=type==="donation";const [f,setF]=useState(initial|| (donation?{donorName:"",flatDetails:"",amount:"",donationDate:today(),paymentMode:"UPI",notes:""}:{title:"",category:"Decoration",amount:"",expenseDate:today(),vendor:"",receiptReference:"",notes:""}));const set=(k,v)=>setF({...f,[k]:v});async function save(e){e.preventDefault();try{if(donation){if(f.id)await updateDonation(Number(year),f.id,{donorName:f.donorName,flatDetails:f.flatDetails,amount:Number(f.amount),donationDate:f.donationDate,paymentMode:f.paymentMode,notes:f.notes});else { if(!Number.isInteger(Number(year))||Number(year)<=0) throw new Error("Please select a valid year."); await addDonation(Number(year),{...f,amount:Number(f.amount)}) }}else{if(f.id)await updateExpenditure(Number(year),f.id,{title:f.title,category:f.category,amount:Number(f.amount),expenseDate:f.expenseDate,vendor:f.vendor,receiptReference:f.receiptReference,notes:f.notes});else { if(!Number.isInteger(Number(year))||Number(year)<=0) throw new Error("Please select a valid year."); await addExpenditure(Number(year),{...f,amount:Number(f.amount)}) }}onSaved()}catch(e){alert(e.message)}}return <Modal title={f.id?(donation?"Edit Donation":"Edit Expenditure"):(donation?"Add Donation":"Add Expenditure")} onClose={onClose}><form className="form-grid" onSubmit={save}>{donation?<><input required placeholder="Donor name" value={f.donorName} onChange={e=>set("donorName",e.target.value)}/><input placeholder="Flat / House" value={f.flatDetails||""} onChange={e=>set("flatDetails",e.target.value)}/><input required type="number" step="0.01" min="0.01" placeholder="Amount" value={f.amount} onChange={e=>set("amount",e.target.value)}/><input required type="date" value={f.donationDate} onChange={e=>set("donationDate",e.target.value)}/><select value={f.paymentMode} onChange={e=>set("paymentMode",e.target.value)}><option>UPI</option><option>CASH</option></select><input placeholder="Notes" value={f.notes||""} onChange={e=>set("notes",e.target.value)}/></>:<><input required placeholder="Expense title" value={f.title} onChange={e=>set("title",e.target.value)}/><select value={f.category} onChange={e=>set("category",e.target.value)}><option>Tent</option><option>Murti</option><option>Food / Prasad</option><option>Decoration</option><option>Sound</option><option>Other</option></select><input required type="number" step="0.01" min="0.01" placeholder="Amount" value={f.amount} onChange={e=>set("amount",e.target.value)}/><input required type="date" value={f.expenseDate} onChange={e=>set("expenseDate",e.target.value)}/><input placeholder="Vendor" value={f.vendor||""} onChange={e=>set("vendor",e.target.value)}/><input placeholder="Receipt reference" value={f.receiptReference||""} onChange={e=>set("receiptReference",e.target.value)}/><input placeholder="Notes" value={f.notes||""} onChange={e=>set("notes",e.target.value)}/></>}<button className="submit">Save</button></form></Modal>}
function Modal({title,onClose,children}){return <div className="overlay"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}

function AdminTable({rows,type,role,year,reload}){const [edit,setEdit]=useState(null);const donation=type==="donation";async function del(id){if(!confirm(`Delete this ${donation?"donation":"expenditure"}?`))return;try{if(donation)await deleteDonation(Number(year),id);else await deleteExpenditure(Number(year),id);reload()}catch(e){alert(e.message)}}return <section className="table-card"><div className="table-head"><h2>{donation?"Donation Ledger":"Expenditure Ledger"}</h2>{role==="ADMIN"&&<button className="small-add" onClick={()=>setEdit({})}><Plus size={15}/> Add</button>}</div><div className="table-scroll"><table><thead><tr>{donation?<><th>Date</th><th>Donor / Flat</th><th>Mode</th><th>Amount</th></>:<><th>Date</th><th>Item / Service</th><th>Category</th><th>Vendor / Receipt</th><th>Amount</th></>}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{donation?<><td>{r.donationDate}</td><td>{r.donorName}{r.flatDetails&&` (${r.flatDetails})`}</td><td>{r.paymentMode}</td><td className="right">{money(r.amount)}</td></>:<><td>{r.expenseDate}</td><td>{r.title}</td><td>{r.category}</td><td>{r.vendor||r.receiptReference||"—"}</td><td className="right">{money(r.amount)}</td></>}<td>{role==="ADMIN"&&<><button className="action edit" onClick={()=>setEdit(r)}>Edit</button><button className="action delete" onClick={()=>del(r.id)}>Delete</button></>}</td></tr>)}</tbody></table></div>{edit&&<Editor type={type} initial={edit.id?edit:undefined} year={year} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);reload()}}/>}</section>}


function UsersPage(){
 const [users,setUsers]=useState([]),[form,setForm]=useState({username:"",password:"",displayName:"",role:"USER"}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=()=>getUsers().then(setUsers).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm({...form,[k]:v});
 async function submit(e){e.preventDefault();setBusy(true);setError("");try{await createUser(form);setForm({username:"",password:"",displayName:"",role:"USER"});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="users-page"><div className="page-heading"><h1>Users</h1><p>Create login accounts for committee members. Passwords are stored as BCrypt hashes.</p></div>{error&&<div className="error">{error}</div>}<div className="users-grid"><section className="table-card"><h2>Create User</h2><form className="form-grid" onSubmit={submit}><input required placeholder="Username" value={form.username} onChange={e=>set("username",e.target.value)}/><input required placeholder="Display name" value={form.displayName} onChange={e=>set("displayName",e.target.value)}/><input required minLength={8} type="password" placeholder="Password (min 8 characters)" value={form.password} onChange={e=>set("password",e.target.value)}/><select value={form.role} onChange={e=>set("role",e.target.value)}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select><button className="submit" disabled={busy}>{busy?"Creating…":"Create User"}</button></form></section><section className="table-card"><h2>Existing Users</h2><div className="table-scroll"><table><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.displayName}</td><td>{u.role}</td><td>{u.active?"Active":"Inactive"}</td></tr>)}{!users.length&&<tr><td colSpan={4}>No users found.</td></tr>}</tbody></table></div></section></div></div>
}

function Authenticated({user,onLogout}){const [page,setPage]=useState("dashboard"),[years,setYears]=useState([]),[year,setYear]=useState(null),[dashboard,setDashboard]=useState(null),[don,setDon]=useState([]),[exp,setExp]=useState([]);async function load(y=year){const ys=await getYears();setYears(ys);const selected=ys.length?(ys.some(x=>Number(x.year)===Number(y))?Number(y):Number(ys[0].year)):null;setYear(selected);if(selected===null){setDashboard(null);setDon([]);setExp([]);return;}const [d,a,b]=await Promise.all([getDashboard(selected),getDonations(selected),getExpenditures(selected)]);setDashboard(d);setDon(a);setExp(b)}useEffect(()=>{load()},[]);useEffect(()=>{if(year)load(year)},[year]);async function close(){if(!Number.isInteger(Number(year))||Number(year)<=0){alert("Please select a valid year.");return;}if(!confirm(`Close ${year}?`))return;try{await closeYear(year);await load(year);alert(`${year} closed successfully.`)}catch(e){alert(e.message)}}const admin=user.role==="ADMIN";return <div className="app"><Sidebar page={page} setPage={setPage} role={user.role}/><div className="main"><Topbar year={year} setYear={setYear} years={years} user={user} onLogout={onLogout}/><main className="content">{page==="dashboard"&&dashboard&&<><div className="page-heading"><h1>Dashboard</h1><p>Financial overview for {year}</p></div><div className="stats"><Stat title="OPENING BALANCE" amount={dashboard.openingBalance} icon={<Wallet/>} type="blue"/><Stat title="TOTAL DONATIONS" amount={dashboard.totalDonations} icon={<Heart/>} type="green" link="View Donations" onClick={()=>setPage("donations")}/><Stat title="TOTAL EXPENDITURE" amount={dashboard.totalExpenditure} icon={<ShoppingCart/>} type="red" link="View Expenditures" onClick={()=>setPage("expenditures")}/><Stat title="AVAILABLE BALANCE" amount={dashboard.availableBalance} icon={<IndianRupee/>} type="yellow"/></div></>}{page==="donations"&&<AdminTable rows={don} type="donation" role={user.role} year={year} reload={()=>load(year)}/>} {page==="expenditures"&&<AdminTable rows={exp} type="expense" role={user.role} year={year} reload={()=>load(year)}/>} {page==="users"&&admin&&<UsersPage/>} {page==="year"&&<div className="year-page"><h1>Year Closure</h1><p>Close {year} and carry its remaining balance into {year+1}.</p><div className="close-box"><b>Available balance: {money(dashboard?.availableBalance)}</b><button disabled={!admin||dashboard?.closed} onClick={close}><LockKeyhole size={17}/> {dashboard?.closed?"Year Closed":"Close Year"}</button></div></div>}</main></div></div>}

export default function App(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[loginPage,setLoginPage]=useState(false);useEffect(()=>{if(localStorage.getItem("token")){validateSession().then(u=>setUser({...JSON.parse(localStorage.getItem("user")||"{}"),...u})).catch(()=>{localStorage.clear()}).finally(()=>setChecking(false))}else setChecking(false)},[]);if(checking)return <div className="login-page"><div className="login-card"><div className="login-diya">🪔</div><h1>Loading…</h1></div></div>;if(loginPage&&!user)return <Login onLogin={setUser} onHome={()=>setLoginPage(false)}/>;if(!user)return <PublicHome onLogin={()=>setLoginPage(true)}/>;return <Authenticated user={user} onLogout={()=>{localStorage.clear();setUser(null)}}/>}
